platform :ios, '15.0'
use_frameworks!

target 'VmqIOS' do
  # 网络库
  pod 'Alamofire', '~> 5.8'
  # 二维码扫描
  pod 'EFQRCode', '~> 6.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
